buildscript {
    ext.kotlin_version = '1.8.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        // classpath "com.android.tools.build:gradle:7.0.2"
        //  classpath 'com.android.tools.build:gradle:7.3.0' // For Gradle 7.x
         classpath 'com.android.tools.build:gradle:8.2.2' 
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
            classpath 'com.android.tools.build:gradle:8.2.2'  // Latest stable as of April 2025
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22" // If using Kotlin
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

    configurations.all {
        resolutionStrategy {
            force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.0'
            force 'org.jetbrains.kotlin:kotlin-reflect:1.8.0'
        }
    }

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
